### PR TITLE
Update OpenCollar - bell.lsl : submenu, to be or not to be?

### PR DESCRIPTION
**Pull request by ghost**
submenu is not used, and can be safely removed, or reserved for future use

### CODE REVIEW

**Comment by littlemousy** [comment]
It's not used by any of the other collar code, but its possible there are 3rd party plugins that DO hook into this menu.  It might be a good idea to ask around before removing this.

**Comment by WendyStarfall** [comment]
It's true but I've been wondering - what else could you possibly want your bell to do? It can now be turned on/off, shown/hidden, adjust volume, adjust frequency, change the sound..

EDIT: There could be a Style thing that has bell types like kitty/cow/classic, I guess

(There is also the help menu in the bell that nags me a bit.. the bell and the badwords help, I will tap into that for an uniform help style. Right now the one gives you green text print, the other makes an info dialog.)

**Comment by ghost** [comment]
Change bell style ? it's interesting. how to implement it?
Change sculpts in one prim?
or several different bells with change alpha?

**Comment by littlemousy** [comment]
I think bells should be defined by the collar designer, so adding sculpt maps by script wouldn't be ideal.  If a designer wanted to offer alternative bell shapes, then different bell prims, changing alpha would be good, IMHO.

**Comment by ghost** [comment]
in this case, need different bell script,
or additional plugin to change the alpha, together with the original bell script

**Pull request closed without merging**
