### PR TITLE
Leash and Stealth

### PR DESCRIPTION
**Pull request by ghost**
I think it will be better to hide the leash when the collar is invisible ?

### CODE REVIEW

**Comment by stawberri** [comment]
While this would be convenient, I think it might still be desirable sometimes to have a visible leash with an invisible collar.

**Comment by WendyStarfall** [comment]
We thought about doing that when creating 4.0 but then quickly realized that a healthy amount of users would wear a stealthed OpenCollar 4.0 above unscripted accessory and ended up not stealthing the leash.

It's still worth considering I think because of the name we chose for hiding the collar, "stealth", it implies going unnoticed which is something a lot of people in our subculture do in their daily lives.

If we expand there it would open possibilities to auto-stealth when in PG zones or under other set conditions. Maybe hiding a collar and stealthing a collar should be two different things.

In any case, I don't volunteer to develop this or explain it to users. Haha! 🙊

**Comment by ghost** [comment]
Need another way...

**Comment by WendyStarfall** [comment]
There should be a difference in between "hide" and "stealth".

I liked your change @RomkaSwallowtail !

**Pull request closed without merging**
