### PR TITLE
Update OpenCollar - menu.lsl  EXIT button ?

### PR DESCRIPTION
**Pull request by ghost**
add EXIT button in Main menu

### CODE REVIEW

**Comment by WendyStarfall** [comment]
I'm not sure we need an EXIT button because we already have -> http://screencast.com/t/cCB8j8ek
What do others think?

**Comment by ghost** [comment]
oh, yeah, but this button is very small :)
old cat looking for a magnifying glass :)
and yes, what do others think? I'm curious :)

**Comment by littlemousy** [comment]
Yes, the [X] is small... I usually use the ignore button, it does the same thing as the [X]. The only difference between that and an "exit" button would be that exit kills the stride in the dialog list.  Personally, I'd rather keep a clean menu than gain a single stride in a list.

**Comment by ghost** [comment]
well, let the menu will be clean

**Pull request closed without merging**
