### PR TITLE
oc_particle.lsl: untargeted dialogue

### PR DESCRIPTION
**Pull request by ghost**
I do not understand why it is needed.
because LM_SETTING_RESPONSE  returns with empty kMessageID, and it causes unacceptable ConfigureMenu dialogue to 'null_key user'.
in this case, it is meaningless.
I comment it for the future
maybe someone has an idea for this purpose

### CODE REVIEW

**Comment by GarvinTwine** [comment]
It is needed for a remenu when clicking Strict in the Configure menu.
Lets do instead of '//' a if (kMessageID) to prevent null_key being passed to dialog when this message comes from the settings script.
you will find in oc_leash at line 
559
`llMessageLinked(LINK_SET, LM_SETTING_RESPONSE, g_sSettingToken + "strict=1,"+ (string)iAuth, kMessageID);` 
568
`llMessageLinked(LINK_SET, LM_SETTING_RESPONSE, g_sSettingToken + "strict=0,"+ (string)iAuth,kMessageID);`
572
`llMessageLinked(LINK_SET, LM_SETTING_RESPONSE,"strictAuthError="+(string)iAuth,kMessageID)`
this is where a valid key is passed for the menu call in 
oc_particle

**Comment by ghost** [comment]
In this case, it is necessary to check the validity kMessageID, because the oc_settings.lsl returns empty key

**Comment by GarvinTwine** [comment]
that's what i said Romka

**Comment by ghost** [comment]
maybe better need to add check kRCPT for NULL_KEY in oc_dialog.lsl ?
this will prevent the opening of any listens for empty or NULL_KEYs 'recipients'
 #760

**Comment by GarvinTwine** [comment]
i think both...
First of all all scripts should make sure to send only valid dialog LMs, that is the responsibility of the scripts that calls for a dialog.
As seen it happens to be forgotten... (which should be fixed! ) it might be good to have a secure check in dialog itself, too.

**Pull request merged**
