### PR TITLE
change the check for existing restrictions when trying to add a new one

### PR DESCRIPTION
**Pull request by GarvinTwine**
issue #972

### CODE REVIEW

**Comment by stawberri** [comment]
Would it be more efficient to add a `§` to the beginning and end of `sSrcRestr` and check for the existence of `§restriction§`?

**Comment by GarvinTwine** [comment]
That would require first to check what other effects such a change would have to other parts of this script and eventual other scripts that might use this. 
I know the print out of "show restrictions" does and would should show as:
This collar (vdTerminal): §detach:top left§§detach:top§
instead of now:
This collar (vdTerminal): detach:top left§detach:top

Cosmetics I guess but well...
I am not sure if either is more or less effective at all here, it's about one if statement that executes 2 ll functions, i guess the llSubStringIndex is a bit faster then to parse and ListFindList but then this might have other changes followed that negotiate the win again...

So I think this fix for a possibly years old little bug nobody even noticed till these days, this is fine

**Comment by stawberri** [comment]
Um, I think I might not have been clear enough! I meant that those symbols could be added during the check. 😅 

``` lsl
if (!~llSubStringIndex("§"+sSrcRestr+"§","§"+sBehav+"§")) {
```

**Comment by GarvinTwine** [comment]
I definitely misunderstood, so here you go :)

**Review by WendyStarfall — APPROVED** [review]
Tested with various sources, this is good to go!

**Pull request merged**
