### PR TITLE
[Video] Visualisation of commits/people working on OpenCollarUpdater

### PR DESCRIPTION
**Pull request by RayZopf**
created with [gource](https://code.google.com/p/gource/)  
August 2013 - February 22. 2014
.mp4 video file, 3 min, 9MB
encoded with ffmpeg/handbrake

```
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42
File size                                : 8,80 MiB
Duration                                 : 2min 47s
Overall bit rate                         : 440 Kbps
Encoded date                             : UTC 2014-02-23 05:29:41
Tagged date                              : UTC 2014-02-23 05:38:26
Writing application                      : HandBrake 5476svn 2013051801

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Ja
Format settings, ReFrames                : 16 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2min 47s
Bit rate                                 : 438 Kbps
Width                                    : 640 Pixel
Height                                   : 400 Pixel
Display aspect ratio                     : 16:10
Frame rate mode                          : konstant
Frame rate                               : 25,000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : progressiv
Bits/(Pixel*Frame)                       : 0.068
Stream size                              : 8,75 MiB (99%)
Writing library                          : x264 core 130 r2273 b3065e6
Encoding settings                        : cabac=1 / ref=16 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2014-02-23 05:29:41
Tagged date                              : UTC 2014-02-23 05:38:26
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
```

### CODE REVIEW

**Comment by WendyStarfall** [comment]
Hey, Ray! Let's host this on YouTube instead, please. I can put it on my channel but better would be you have it on your's - then let's add it as link in the readme.md

Thanks =)

**Comment by RayZopf** [comment]
np, just put it on yours :)
tell me when you're done, so that I can move the file out of repo

**Comment by RayZopf** [comment]
Hey Hey :)  
As i didn't get further notice, here my roadmap:  
With next OC repo change, i'll reset my repo's main branch to stay in sync - above video file then could be found in branch video - video folder

**Comment by WendyStarfall** [comment]
It's on YouTube! Sorry for letting you wait so long, there was just too much going on.
https://www.youtube.com/watch?v=gArfKk9wOwE

**Pull request closed without merging**
