### PR TITLE
Update OpenCollar - rlvmisc.lsl

### PR DESCRIPTION
**Pull request by NorthGlenwalker**
To add support of "Force Mouselook" using new RLV 2.9 API to rlvmisc

### CODE REVIEW

**Comment by WendyStarfall** [comment]
I still need to test this because I'm not sure if camdistmax/min will work without a value for distance which would be 0 for mouselook, I guess?

Anyway, slut is working on a rlvview bundle which will include stuff like that! :see_no_evil:

**Comment by NorthGlenwalker** [comment]
I tried a distance value and could not get it to work, but it worked ok with no value set.... but yes 2.9 has a number of new intresting extra's

**Comment by WendyStarfall** [comment]
Yes, I agree. There would be a few things in 2.9 that could be used for fun on-the-fly RLV play. Until FS doesn't bump their RLV API to 2.9 though, we still end up with a lot of users asking why it won't work. :unamused:

**Comment by WendyStarfall** [comment]
Let's add in the manual that this feature requires a 2.9 API

**Pull request merged**
