### PR TITLE
Update OpenCollar - bell.lsl  little grooming

### PR DESCRIPTION
**Pull request by ghost**
rem unused MESSAGE MAP.
rearrange menu buttons.
add ResetScript on_rez, because all settings are loaded.
556-569: apply bell settings after loading.

### CODE REVIEW

**Comment by littlemousy** [comment]
Why do we need to reset the script on rez?  That seems like a bunch of extra work for the server that isn't needed.

**Comment by ghost** [comment]
permission control will resets after reattach or relog, but some variables like g_iHasControl stay TRUE.
and script can't take control again, when settings loaded.

p.s. many scripts are resetts on_rez, why not ?

**Comment by JoyStipe** [comment]
permission_trigger_ ... it is gone on rez but the sound may still be active
within the script. same issue will occur with animations scripts - you'll
notice it in debug box on your viewer if/when it happens

On Tue, Apr 22, 2014 at 1:21 PM, littlemousy notifications@github.comwrote:

> Why do we need to reset the script on rez? That seems like a bunch of
> extra work for the server that isn't needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OpenCollar/OpenCollarUpdater/pull/235#issuecomment-41090677
> .

## 

~ A bug is a feature with seniority

**Comment by littlemousy** [comment]
The code in git already works fine getting permission to take controls, both on login, and on rewear/rez.  What do you mean "script can't take control again, when settings loaded."

**Comment by ghost** [comment]
both variants work fine:
     on_rez(integer param)
     {
         g_kWearer=llGetOwner();
         g_sSubPrefix=AutoPrefix();
         if (g_iBellOn) llRequestPermissions(g_kWearer,PERMISSION_TAKE_CONTROLS);
    }
or 
     on_rez(integer param)
     {
          llResetScript();
     }

we can not use the llResetScript 
p.s. return to first (old) variant

**Pull request closed without merging**
